### ISSUE TITLE
Point Cloud Exponential Function - Implementation Inconsistency

### ISSUE THREAD

**Issue by AxelGiottonini** [wdiepeveen/Riemannian-geometry-for-efficient-analysis-of-protein-dynamics-data#1]
Hey !
Shouldn't the following line use the argument base and not the instance base?

https://github.com/wdiepeveen/Riemannian-geometry-for-efficient-analysis-of-protein-dynamics-data/blob/d7dec9304a45358bb608466668aedfd6f49b6abd/src/manifolds/pointcloud.py#L122

**Comment by wdiepeveen** [comment]
Hi,

This part of the code is called if base is not None. So it assumes that the user provides a base. If not, self.base_point is called, which happens in else.

I hope this helps!

All the best,

Willem

On 19 Nov 2024, at 01:20, AxelGiottonini ***@***.***> wrote:



Hey !
Shouldn't the following line use the argument base and not the instance base?

https://github.com/wdiepeveen/Riemannian-geometry-for-efficient-analysis-of-protein-dynamics-data/blob/d7dec9304a45358bb608466668aedfd6f49b6abd/src/manifolds/pointcloud.py#L122

**Comment by AxelGiottonini** [comment]
Sorry, I should have written more details, it appears that my issue is not clear.

According to the `s_geodesic` implementation, when you call `s_geodesic(self, x, y, tau, base=None, step_size=1., ...)` function without specifying the base (i.e. `base=None`), you use the instance base, what is implemented in the `if-else` statement.

According to the `s_exp` implementation, when you call ` s_exp(self, x, X, c=1/4, base=None,...) `function without specifying the base, you use the instance base, what is also implemented in the `if-else` statement.

Now let's assume we are in the `s_exp` function and that the argument base is not none. We go into the while loop and compute the `x_new` calling the `s_geodesic` function. As written in the `s_exp` implementation, the `s_geodesic` function is called without specifying the base. The `s_geodesic` call without specifying the base calls the `s_geodesic` with the instance base. Thus, the `s_exp` function using an argument basis is built with the `s_geodesic` function with the instance base.

```
obj.s_exp(..., base=torch.Tensor(...), ...) -> obj.s_geodesic(..., base=None, ...) -> obj.s_geodesic(..., base=obj.base_point, ...)
```

Such implementation would be correct when the geodesic is invariant to the base and thus the argument base or the instance base return the same result, but I don't remember such statement in your article.

In the code, I would thus replace the line 122 and 123 by
```{python}
x_new = self.s_geodesic(
    xkk, xk, torch.tensor([2.]),
    base=base, step_size=step_size, max_iter=max_iter, tol=tol,
    debug=debug
)
```

**Comment by wdiepeveen** [comment]
Hi,

Thanks for clarifying. I understand your question now. In short: During computing the exponential steps, the base does not matter. Only at the end, we have to align it to the base (l.128).

In more detail: What you get out of l.122 is a new point that can have any orientation (you get an element in the equivalence class). For computing the next step, this does not matter as the geodesic are formally defined over the quotient space. So any orientation of either input will give you the same output (op to global euclidean transformation). However, by the end of the exp computation, you might want to align it to some specific basis (as the iterates in between have not been aligned). So this is what you do in l.128.

I hope this helps!

All the best,

Willem

On 19 Nov 2024, at 22:47, AxelGiottonini ***@***.***> wrote:



Sorry, I should have written more details, it appears that my issue is not clear.

According to the s_geodesic implementation, when you call s_geodesic(self, x, y, tau, base=None, step_size=1., ...) function without specifying the base (i.e. base=None), you use the instance base, what is implemented in the if-else statement.

According to the s_exp implementation, when you call s_exp(self, x, X, c=1/4, base=None,...)function without specifying the base, you use the instance base, what is also implemented in the if-else statement.

Now let's assume we are in the s_exp function and that the argument base is not none. We go into the while loop and compute the x_new calling the s_geodesic function. As written in the s_exp implementation, the s_geodesic function is called without specifying the base. The s_geodesic call without the specifying the base calls the s_geodesic with the instance base. Thus, calling the s_exp function using an argument basis is build with the s_geodesic function with the instance base.

obj.s_exp(..., base=torch.Tensor(...), ...) -> obj.s_geodesic(..., base=None, ...) -> obj.s_geodesic(..., base=obj.base_point, ...)


Such implementation would be correct when the geodesic is invariant to the base and thus the argument base or the instance base return the same result, but I don't remember such statement in your article.

**Comment by AxelGiottonini** [comment]
Thank you very much for the clarification !

An by the way, it's a very nice paper, I really enjoyed going through it !

**Comment by wdiepeveen** [comment]
No worries! And glad to hear you enjoyed the paper :)

All the best,

Willem

On Nov 21, 2024, at 22:20, AxelGiottonini ***@***.***> wrote:

﻿

Thank you very much for the clarification !

An by the way, it's a very nice paper, I really enjoyed going through it !
